# Generated by Django 6.0.5 on 2026-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_credit_order_useractivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='last_login_time',
            new_name='last_seen',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
