# Generated by Django 6.0.5 on 2026-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_last_login_time_useractivity_last_seen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='session_start',
            new_name='last_login_time',
        ),
    ]
