# Generated by Django 6.0.5 on 2026-05-28 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_session_start_useractivity_last_login_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='credit',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 4, 12, 34, 21, 834636, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivering', 'Delivering'), ('done', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
