# Generated by Django 6.0.5 on 2026-05-28 14:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_owner_alter_order_delivery_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('buyer', 'car')},
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 4, 14, 1, 10, 90141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='created_at',
        ),
    ]
