# Generated by Django 6.0.5 on 2026-06-02 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_order_latitude_order_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 9, 20, 39, 24, 17889, tzinfo=datetime.timezone.utc)),
        ),
    ]
